/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
*/

import React, { useEffect, useRef } from "react";
import { useGLTF, useAnimations } from "@react-three/drei";
import { useFrame } from "react-three-fiber";

export default function Car(props) {
  const group = useRef();
  const { nodes, materials, animations } = useGLTF("/car.gltf");
  const { actions } = useAnimations(animations, group);

  useEffect(() => {}, []);

  return (
    <group ref={group} {...props} dispose={null}>
      <group name="Scene">
        <group name="Collection_2">
          <mesh
            name="Cylinder_1"
            castShadow
            receiveShadow
            geometry={nodes.Cylinder_1.geometry}
            material={nodes.Cylinder_1.material}
            position={[-0.63, 0, 0]}
            rotation={[0, 0, Math.PI / 2]}
            scale={[0.29, -0.12, 0.29]}
          />
          <mesh
            name="Cylinder001_1"
            castShadow
            receiveShadow
            geometry={nodes.Cylinder001_1.geometry}
            material={nodes.Cylinder001_1.material}
            position={[0.63, 0, 0]}
            rotation={[0, 0, Math.PI / 2]}
            scale={[0.29, -0.12, 0.29]}
          />
          <mesh
            name="Cylinder002_1"
            castShadow
            receiveShadow
            geometry={nodes.Cylinder002_1.geometry}
            material={nodes.Cylinder002_1.material}
            position={[0.63, 0, -1.44]}
            rotation={[0, 0, Math.PI / 2]}
            scale={[0.29, -0.12, 0.29]}
          />
          <mesh
            name="Cylinder003_1"
            castShadow
            receiveShadow
            geometry={nodes.Cylinder003_1.geometry}
            material={nodes.Cylinder003_1.material}
            position={[-0.63, 0, -1.44]}
            rotation={[0, 0, Math.PI / 2]}
            scale={[0.29, -0.12, 0.29]}
          />
          <mesh
            name="Cube_1"
            castShadow
            receiveShadow
            geometry={nodes.Cube_1.geometry}
            material={nodes.Cube_1.material}
            position={[0, 0.25, -0.74]}
            scale={[0.55, 0.26, 1]}
          />
          <mesh
            name="Cube001_1"
            castShadow
            receiveShadow
            geometry={nodes.Cube001_1.geometry}
            material={nodes.Cube001_1.material}
            position={[0, 0.74, -1.26]}
            scale={[0.55, 0.26, 0.48]}
          />
        </group>
        <mesh
          name="Cylinder"
          castShadow
          receiveShadow
          geometry={nodes.Cylinder.geometry}
          material={nodes.Cylinder.material}
          position={[-0.63, 0, 0]}
          rotation={[0, 0, Math.PI / 2]}
          scale={[0.29, -0.12, 0.29]}
        />
        <mesh
          name="Cylinder001"
          castShadow
          receiveShadow
          geometry={nodes.Cylinder001.geometry}
          material={nodes.Cylinder001.material}
          position={[0.63, 0, 0]}
          rotation={[0, 0, Math.PI / 2]}
          scale={[0.29, -0.12, 0.29]}
        />
        <mesh
          name="Cylinder002"
          castShadow
          receiveShadow
          geometry={nodes.Cylinder002.geometry}
          material={nodes.Cylinder002.material}
          position={[0.63, 0, -1.44]}
          rotation={[0, 0, Math.PI / 2]}
          scale={[0.29, -0.12, 0.29]}
        />
        <mesh
          name="Cylinder003"
          castShadow
          receiveShadow
          geometry={nodes.Cylinder003.geometry}
          material={nodes.Cylinder003.material}
          position={[-0.63, 0, -1.44]}
          rotation={[0, 0, Math.PI / 2]}
          scale={[0.29, -0.12, 0.29]}
        />
        <mesh
          name="Cube"
          castShadow
          receiveShadow
          geometry={nodes.Cube.geometry}
          material={nodes.Cube.material}
          position={[0, 0.25, -0.74]}
          scale={[0.55, 0.26, 1]}
        />
        <mesh
          name="Cube001"
          castShadow
          receiveShadow
          geometry={nodes.Cube001.geometry}
          material={nodes.Cube001.material}
          position={[0, 0.74, -1.26]}
          scale={[0.55, 0.26, 0.48]}
        />
      </group>
    </group>
  );
}

useGLTF.preload("/car.gltf");
